### ISSUE TITLE
Steps for using the repo

### ISSUE THREAD

**Issue by juc023** [mi150/RegenHance#1]
Thank you for your open-source. Can you please add some steps to use your code? 
Looking forward to it!

**Comment by mi150** [comment]
I apologize, the code is not yet in its final state. We are currently focused on meeting the NSDI '25 deadline, but we will improve the code repository once the submission is complete. Thank you for your understanding.

**Comment by mi150** [comment]
I apologize, the code is not yet in its final state. We are currently focused on meeting the NSDI '25 deadline, but we will improve the code repository once the submission is complete. Thank you for your understanding.
